### ISSUE TITLE
Codeship should actually run the tests

### ISSUE THREAD

**Issue by mattr555** [HTHS/hths-lunch#16]
Probably just by adding `npm install` to the setup script and `npm test` to the test script

Also, not sure if the tests should run in parallel; they kind of create a confusing output

**Comment by ilanbiala** [comment]
https://codeship.com/projects/41783/builds/3734405 the tests do run.

**Comment by mattr555** [comment]
Really? The build only runs for < 1 minute, which doesn't make sense to download everything and run. Nothing seems to be output in the logs, and there are no commands in the config: 

![](http://i.imgur.com/IxsmN3D.png)

**Comment by ilanbiala** [comment]
Build takes 2m 36s and I have all that defined, I'm not sure why it's blank for you.

**Comment by mattr555** [comment]
Interesting, well I chose node from the drop down and it worked
